# Generated by Django 3.1.5 on 2021-02-03 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersnips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snipdes',
            new_name='snip_description',
        ),
        migrations.AddField(
            model_name='snippet',
            name='snip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
