# Generated by Django 3.1.5 on 2021-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersnips', '0002_auto_20210203_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snip_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
