# Generated by Django 3.1.5 on 2021-02-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersnips', '0004_auto_20210203_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='topic_description',
            field=models.TextField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snip_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
